---
- name: Configure webserver with tomcat
  hosts: agent
  become: true
  tasks:
  - name: copy web page template
    template:
     src: index.html
     dest: /var/lib/tomcat9/webapps/demo
  - name: copying
    copy:
     src: images
     dest: /var/lib/tomcat9/webapps/demo
  - name: tomcat
    service:
     name: tomcat9
     state: started

